titre: titleForm,
      categorie: categoryForm,
      ingredient0: ingredientList[0].ingredient || null,
      ingredient1: ingredientList[1].ingredient || null,
      ingredient2: ingredientList[2].ingredient || null,
      ingredient3: ingredientList[3].ingredient || null,
      ingredient4: ingredientList[4].ingredient || null,
      ingredient5: ingredientList[5].ingredient || null,
      ingredient6: ingredientList[5].ingredient || null,
      ingredient7: ingredientList[7].ingredient || null,
      ingredient8: ingredientList[8].ingredient || null,
      ingredient9: ingredientList[9].ingredient || null,
      ingredient10: ingredientList[10].ingredient || null,
      ingredient11: ingredientList[11].ingredient || null,
      ingredient12: ingredientList[12].ingredient || null,
      ingredient13: ingredientList[13].ingredient || null,
      ingredient14: ingredientList[14].ingredient || null,
      etape0: stepList[0].step || null,
      etape1: stepList[1].step || null,
      etape2: stepList[2].step || null,
      etape3: stepList[3].step || null,
      etape4: stepList[4].step || null,
      etape5: stepList[5].step || null,
      etape6: stepList[6].step || null,
      etape7: stepList[7].step || null,
      etape8: stepList[8].step || null,
      etape9: stepList[9].step || null,
      etape10: stepList[10].step || null,
      etape11: stepList[11].step || null,
      etape12: stepList[12].step || null,
      etape13: stepList[13].step || null,
      etape14: stepList[14].step || null,
      imagerecette: imageForm,